Feature/api
raz-joan/rancid-tomatillos pull request #4
Opened 2021-12-04 21:43 UTC by tonydhsu

What (if any) features are you implementing?
- Hooked up all api fetch calls
- Display all movie details correctly
- Display each movie trailer correctly

What (if anything) did you refactor?

Were there any issues that arose?
- Unique keys warning in console.

2021-12-04 21:46 UTC, raz-joan commented on src/App.js
> -import movieData from './movieData'
Nice catch on removing this unnecessary file!

2021-12-04 21:47 UTC, raz-joan commented on src/App.js
We can probably refactor these fetch calls to be a single dynamic function in another file when there is time. This will make this file a lot shorter.

2021-12-04 21:47 UTC, raz-joan commented on src/App.js
> +      return (
I like the way this error will be shown so that the other return isn't rendered at all.

2021-12-04 21:50 UTC, raz-joan commented on src/MovieCard.js
> +        <Movie poster={props.movie.poster_path} title={props.movie.title} key={Date.now()}/>
Let's both look at this to figure out the error that we're getting with these 'key' attributes.

2021-12-04 21:50 UTC, raz-joan commented on src/MovieCard.js
> +        <iframe width="560" height="315" src={`https://www.youtube.com/embed/${props.trailer}`} title="YouTube video player" frameBorder="2" allow="accelerometer; autoplay; clipboard-write; encrypted
Nice use of interpolation here!

2021-12-04 21:52 UTC, raz-joan commented on src/App.js
> +        this.setState({ trailer: data.videos[0].key, error: '' })
We'll need to fix this to find the first movie that matches type='trailer'.

2021-12-04 21:53 UTC, raz-joan requested changes
Awesome work. We made a lot of progress today. Now we just have to figure out the two bugs:
- the key attributes on <Movie /> and <MovieInfo /> withing MovieCard.js
- add .find() to the received movies to correctly select a 'trailer' to show to the user

2021-12-05 18:43 UTC, merged

2021-12-07 22:57 UTC, kaylagordon reviewed
Everything looks great! No need to change anything, these are all just considerations :)

2021-12-07 22:57 UTC, kaylagordon commented on src/App.js
> +    fetch('https://rancid-tomatillos.herokuapp.com/api/v2/movies')
Consider moving fetch calls to their own file

2021-12-07 22:57 UTC, kaylagordon commented on src/App.js
> +        this.setState({ movies: data.movies, error: '' })
great job updating two pieces of state in one line!

2021-12-07 22:57 UTC, kaylagordon commented on src/App.js
YAS

2021-12-07 22:57 UTC, kaylagordon commented on src/MovieCard.js
>  const MovieCard =(props) => {
consider destructutring here so you don't have to type `props.` over and over

2021-12-07 22:57 UTC, kaylagordon commented on src/MovieInfo.js
> +      <p>Rating: {(props.rating).toFixed(1)}</p>
same as above - destructure your props